resources:
- repo: self

trigger: none

jobs:
- job: Stage_TiP_Test_Notebooks
  cancelTimeoutInMinutes: 0
  pool:
    vmImage: ubuntu-20.04
  steps:
    - template: templates/conda.yml
    - template: templates/get_cst_notebooks.yml