resources:
- repo: self

trigger: none

variables:
- name: targetChannel
  value: cst
- name: storageAccountName
  value: kyrushdevadls

jobs:
- job: Stage_TiP_Test_Notebooks
  cancelTimeoutInMinutes: 0
  pool:
    vmImage: ubuntu-20.04
  steps:
    - template: templates/conda.yml
    - template: templates/get_cst_notebooks.yml
    - task: AzureCLI@1
      displayName: Az File Copy to Storage
      inputs:
        azureSubscription: kyrush-devtest-rg
        scriptLocation: inlineScript
        inlineScript: |
          az storage blob upload-batch \
            --destination \tip-notebooks-$(Build.BuildNumber) \
            --account-name "$(storageAccountName)" \
            --source "$(Build.ArtifactStagingDirectory)/notebook-artifacts-staging/$(targetChannel)"